"""Fixing Field Lengths

Revision ID: 206a6b550620
Revises: 7279fa4c7f91
Create Date: 2022-05-11 01:18:12.427138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206a6b550620'
down_revision = '7279fa4c7f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fromCurrency', sa.String(length=3), nullable=False),
    sa.Column('toCurrency', sa.String(length=3), nullable=False),
    sa.Column('fromValue', sa.String(length=20), nullable=False),
    sa.Column('toValue', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.String(length=15), nullable=False),
    sa.Column('date_saved', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Conversions')
    # ### end Alembic commands ###
