"""Adding is_Admin

Revision ID: 2b06e1d4e3ba
Revises: 206a6b550620
Create Date: 2022-05-17 18:50:07.035671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b06e1d4e3ba'
down_revision = '206a6b550620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_Admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_Admin')
    # ### end Alembic commands ###
