"""Initial migration.

Revision ID: 7279fa4c7f91
Revises: 
Create Date: 2022-05-11 00:59:18.365126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7279fa4c7f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fromCurrency', sa.String(length=256), nullable=False),
    sa.Column('toCurrency', sa.String(length=256), nullable=False),
    sa.Column('fromValue', sa.String(length=256), nullable=False),
    sa.Column('toValue', sa.String(length=256), nullable=False),
    sa.Column('rate', sa.String(length=256), nullable=False),
    sa.Column('date_saved', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('users')
    op.drop_table('conversions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fromCurrency', sa.VARCHAR(length=256), nullable=False),
    sa.Column('toCurrency', sa.VARCHAR(length=256), nullable=False),
    sa.Column('fromAmount', sa.VARCHAR(length=256), nullable=False),
    sa.Column('rate', sa.VARCHAR(length=256), nullable=False),
    sa.Column('date_saved', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('Users')
    op.drop_table('Conversions')
    # ### end Alembic commands ###
